app:
  name: e_com_api

#database
spring:
  datasource:
    url: jdbc:mysql://nozomi.proxy.rlwy.net:50993/ecom_db_cloud?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: EULnrwNfsISbejzIAflzOfxQSMMptbGA
    tomcat:
      initial-size: 10
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 5
    hikari:
      connection-timeout: 120000
      idle-timeout: 60000
      max-lifetime: 120000
      minimum-idle: 2
      maximum-pool-size: 4   
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  main: 
    allow-circular-references: true

entitymanager:
  packagesToScan: com.e_com

#File upload location in C drive    
#fileupload:
#  url: /e_com/
#  path: 

#file:
#  upload.location: /Uploads

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    #    eureka-service-url-poll-interval-seconds: 0
#    serviceUrl:
#      defaultZone: http://localhost:7000/eureka/

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 160000000
#        readTimeout: 160000000
