spring:
  application:
    name: e_com_api
  profiles:
    active: "prod"
  mail:
    host: smtp.gmail.com
    port: 587
    username: "deltapos.codearson@gmail.com"
    password: "ttbi wpim bfko qpls"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  
# JWT Configuration
pos:
  web:
    jwtSecret: "357638792F423F4428472B4B6250655368566D597133743677397A2443264629"

logging:
  file:
    path: "log"

# AI service
huggingface:
  api:
    key: huggingface_api_key
